version: '3.8'

services:
  weather-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
